AllCops:
  RunRailsCops: true
  Exclude:
    - bin/*
    - config/initializers/*
    - db/migrate/*
    - db/schema.rb
    - Guardfile

Blocks:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Exclude:
    - config/**/*
    - db/seeds.rb
    - Rakefile
    - script/rails

MethodLength:
  Max: 15
