# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26d71caf38f5b62e1a434c2bded8da98c6780a669e02e3634f17a4324422c26cf9838a9e2d52bee8b8051eb960aa95f8c784d440ed60443d6e8dca6c49f77bc0

test:
  secret_key_base: 69caa0f5a2542825076c9ec2ff667b73186842bed93d6b1322520671fe9f8338f9a0a1ab28a066fd8cf71696bb9b4fdfc835c02eeb5e46072e1d7da2b5cef110

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
